name = "natural-nagas"
compatibility_date = "2024-09-09"
pages_build_output_dir = "./dist"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[vars]
# Add any environment variables here if needed